### ISSUE TITLE
1.0 compatibility

### ISSUE THREAD

**Issue by zlsa** [VenVen/Stock-Revamp#28]
Does not work with 1.0 (no parts are overridden).

I know it will probably take a while to make it compatible, but I just wanted to create an issue to reference.

**Comment by VenVen** [comment]
Thats odd... When I loaded everything up in an otherwise fresh install of 1.0, all the parts worked aside from some sizing and node issues. Were you running any other mods with Stock Revamp? Do you have the latest release of Module Manager? Is their more than one version of Module Manager in your GameData folder?

**Comment by zlsa** [comment]
Can confirm, works properly in a fresh install.

So it turns out I had previously installed, then removed, another mod that included Module Manager via CKAN and CKAN had added, then removed, Module Manager. (When installing Ven's Stock Revamp, I didn't unpack the included MM since there was already one there.)

This is entirely my fault; sorry for wasting your time.

**Comment by zlsa** [comment]
Also, the parts are beautiful.

**Comment by VenVen** [comment]
No problem, glad to help!

Ven~
