### ISSUE TITLE
Releasing the 2.5m pod cover Explodes everything.

### ISSUE THREAD

**Issue by kiwivogel** [VenVen/Stock-Revamp#60]
Decoupling the 2.5m pod cover releases a lot of energy and results in everything flying of the 2.5m pod  (this includes the heat shield and docking port), decouping the cover via the docking port has the same result. This seems to be unrelated to aerodynamic forces as it occurs inside and outside of the atmosphere.

**Comment by blowfishpro** [comment]
Possible explanation (not yet investigated): If the cover has a concave collider, then that would be forced to be convex in 1.0.5, and thus would clip into the pod and other things.  Once the cover is decoupled, then it's part of a separate vessel and thus can interact with the pod's collider, and since they overlap, weird things happen.

**Comment by kiwivogel** [comment]
Yeah, seems like a collider issue.

**Comment by VenVen** [comment]
Yeah @blowfishpro, that was the issue. I've redone the collider so this shouldn't happen anymore.

@kiwivogel, thank you for reporting this issue! :)
