### ISSUE TITLE
Mk1-2 RCS thruster locations

### ISSUE THREAD

**Issue by blowfishpro** [VenVen/Stock-Revamp#77]
It seems that the current thruster locations provide almost no pitch or yaw torque.  Presumably the intention is for the thrusters to provide translation while the reaction wheels provide rotation, but I find that having RCS rotation on some re-entries is actually quite useful when the reaction wheels don't provide enough torque to get the angle I want (or just low on EC).  It also matters in RO, where you don't have reaction wheels and thus are left with almost no pitch/yaw control.

The simplest solution would be to just move the reverse thrusters to the outer ring ... maybe replace the forward thrusters, since they don't provide much thrust anyway?

**Comment by NathanKell** [comment]
@VenVen just to add on here, this would be very helpful. :)

**Comment by VenVen** [comment]
Moving the ports themselves isn't something I'm keen on doing, because I'd have to re-do the pod's side and the ports themselves. However, angling the thrust transforms up would give the pod more yaw and pitch power, but would also reduce the efficiency of the thrusters in other situations.

That and I feel lazy, so that's probably all I'll do. :p

**Comment by VenVen** [comment]
Alright, I've increased the angle of the side RCS thruster by 20 degrees in the latest commit, Hopefully that'll be enough.

**Comment by blowfishpro** [comment]
That should be enough.  I don't see the commit though - maybe push and I can test?

**Comment by blowfishpro** [comment]
Hmm ... the last commit seems to have removed the model.  Am I going crazy here?
