### ISSUE TITLE
Missing plumes from engines

### ISSUE THREAD

**Issue by mbartelsm** [VenVen/Stock-Revamp#97]
What more can I add? there are no plumes and I have no mods that modify plumes. If you need me to do something specific just tell me.

**Comment by thomas15v** [comment]
Have you tried this branch: https://github.com/IronCretin/Stock-Revamp. I only have tried the basic engines and so far I can remember I have some plumes.

**Comment by IronCretin** [comment]
That happens on my branch too. Have you ever had any plume mods installed? Sometimes they don't uninstall completely, and the plumes are removed, but there's nothing to replace them.

**Comment by Kerbas-ad-astra** [comment]
It might even be some third-party mod with an incorrectly written plume patch, e.g. something saying FOR[X] instead of NEEDS[X], which tricks every other NEEDS[X] patch into running even if you don't have X itself installed.  Do you perhaps have SSR Microsat installed?  That one had a misbehaving patch that I caught and fixed myself, but obviously the releases that everyone else downloads still has the problem.

**Comment by benjwgarner** [comment]
@Kerbas-ad-astra It's too bad that it's named FOR[X] instead of FROM[X], PARTOF[X], or PROVIDES[X]. I suppose it's too late for that change to MM at this point. 😛 Thanks for pointing out the SSR Microsat problem. I just went in and looked at the patches, and that error is made several times. This explains a lot. Other mods were acting like HotRockets was installed, and I had forgotten about the FOR[X] tag.

@mbartelsm and **anyone else having this problem**:
To see if this is happening (rather than grep-ing all of the .cfg files in the GameData folder), you can set up a config that changes, say, the title of the Mk1 command pod to "ur c0nf1gz r f00b4r m8" with a NEEDS[PhantomModNameHere] to see if that's what's going on. Of course, it also checks for .dlls and folders in GameData (but not subdirectories) for the name as well, but it's easy to check for those first before copying in 1337test.cfg 😄 Empty mod folders will sometimes be left behind (CKAN used to be pretty bad about this, but now it only does that when there's a plugin data .xml file to save preeferences for the mod you've customized).

Copypaste this into a text file, and save it as 1337test.cfg (anything with .cfg works, though) in GameData (you need ModuleManager, of course, but you must have it already to have this problem anyway). Change "PhantomModNameHere" to whatever you want to check for. For plumes; HotRockets, RealPlume, and SmokeScreen are good ones to begin by searching for using this method.

`@PART[mk1pod]:NEEDS[PhantomModNameHere]`
`{`
`    @title = ur c0nf1gz r f00b4r m8`
`}`

Start the game. If your Mk1 pod has been renamed, somebody put a FOR[X] in a .cfg where it really needed a NEEDS[X]. (You checked for .dlls and mod folders first, didn't you?)
